print('hello from AWESOME Ellen')
print('Ellen is so cool yay')
name = input('What is your name? ')
color = input('What is your favorite color? ')
print(name + ' likes ' + color)
birth_year = input('Birth year: ')
age = 2019 - int(birth_year)
print(type(birth_year))
print(type(age))
print(age)
print('Yay you successfully past the test')